# Generated by Django 4.2.6 on 2023-10-19 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("simbir_go_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_be_rented", models.BooleanField(default=True)),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("Car", "Car"),
                            ("Bike", "Bike"),
                            ("Scooter", "Scooter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=50)),
                ("identifier", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "minute_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "day_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rent_type",
                    models.CharField(
                        choices=[("Minutes", "Minutes"), ("Days", "Days")],
                        max_length=10,
                    ),
                ),
                (
                    "price_of_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("rental_time", models.DurationField(blank=True, null=True)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="simbir_go_app.transport",
                    ),
                ),
            ],
        ),
    ]
