# Generated by Django 4.2.6 on 2023-10-19 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simbir_go_app", "0002_transport_rent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simbirgouser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="simbirgouser",
            name="user_permissions",
        ),
    ]
