# Generated by Django 4.2.6 on 2023-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simbir_go_app", "0003_remove_simbirgouser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="latitude",
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transport",
            name="longitude",
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
