# Generated by Django 4.2.6 on 2023-10-19 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simbir_go_app", "0004_alter_transport_latitude_alter_transport_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="start_time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="transport",
            name="latitude",
            field=models.DecimalField(
                decimal_places=9,
                max_digits=12,
                validators=[
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(-90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="longitude",
            field=models.DecimalField(
                decimal_places=9,
                max_digits=12,
                validators=[
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                ],
            ),
        ),
    ]
