# Generated by Django 4.2.6 on 2023-10-21 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "simbir_go_app",
            "0005_alter_rent_start_time_alter_transport_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="rental_time",
        ),
        migrations.RemoveField(
            model_name="simbirgouser",
            name="last_login",
        ),
    ]
